// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"subgraph/models"
)

type Account struct {
	ID      int              `json:"id"`
	Reviews []*models.Review `json:"reviews"`
}

func (Account) IsEntity() {}

type Product struct {
	ID      int              `json:"id"`
	Reviews []*models.Review `json:"reviews"`
}

func (Product) IsEntity() {}
