services:
  gateway:
    container_name: federation_gateway
    build:
      context: .
      dockerfile: docker/gateway/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./gateway:/var/www/
    depends_on:
      - accounts
      - products
      - reviews

  accounts:
    container_name: federation_accounts
    build:
      context: .
      dockerfile: docker/accounts/Dockerfile
    ports:
      - "10082:8082"
    volumes:
      - ./accounts:/go/src/app
    environment:
      - POSTGRESQL_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@federation_postgres:5432/federation_accounts?sslmode=disable
      - PSQL_PASS=${POSTGRES_PASSWORD}
      - PSQL_USER=${POSTGRES_USER}
      - PSQL_DB=federation_accounts
      - PSQL_HOSTNAME=federation_postgres

  products:
    container_name: federation_products
    build:
      context: .
      dockerfile: docker/accounts/Dockerfile
    ports:
      - "10083:8083"
    volumes:
      - ./products:/go/src/app
    environment:
      - POSTGRESQL_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@federation_postgres:5432/federation_products?sslmode=disable
      - PSQL_PASS=${POSTGRES_PASSWORD}
      - PSQL_USER=${POSTGRES_USER}
      - PSQL_DB=federation_products
      - PSQL_HOSTNAME=federation_postgres

  reviews:
    container_name: federation_reviews
    build:
      context: .
      dockerfile: docker/accounts/Dockerfile
    ports:
      - "10084:8084"
    volumes:
      - ./reviews:/go/src/app
    environment:
      - POSTGRESQL_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@federation_postgres:5432/federation_reviews?sslmode=disable
      - PSQL_PASS=${POSTGRES_PASSWORD}
      - PSQL_USER=${POSTGRES_USER}
      - PSQL_DB=federation_reviews
      - PSQL_HOSTNAME=federation_postgres

  router:
    container_name: federation_router
    image: ghcr.io/apollographql/router:v1.2.0
    restart: "always"
    ports:
      - "4000:4000"
    depends_on:
      - accounts
      - products
      - reviews
    environment:
      APOLLO_ROUTER_SUPERGRAPH_PATH: /apollo-router/schema/supergraph.graphql
      APOLLO_ROUTER_CONFIG_PATH: /apollo-router/config/router.yaml
      APOLLO_ROUTER_LOG: debug
      APOLLO_TELEMETRY_DISABLED: 1
    volumes:
      - ./router/supergraph.graphql:/apollo-router/schema/supergraph.graphql
      - ./router/router.yaml:/apollo-router/config/router.yaml

  postgres:
    container_name: federation_postgres
    image: postgres:14.5
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}