// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"accounts/models"
)

type Review struct {
	ID     int             `json:"id"`
	UserID int             `json:"user_id"`
	Author *models.Account `json:"author"`
}

func (Review) IsEntity() {}
