// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("AccountProfiles", testAccountProfiles)
	t.Run("Accounts", testAccounts)
}

func TestDelete(t *testing.T) {
	t.Run("AccountProfiles", testAccountProfilesDelete)
	t.Run("Accounts", testAccountsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("AccountProfiles", testAccountProfilesQueryDeleteAll)
	t.Run("Accounts", testAccountsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("AccountProfiles", testAccountProfilesSliceDeleteAll)
	t.Run("Accounts", testAccountsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("AccountProfiles", testAccountProfilesExists)
	t.Run("Accounts", testAccountsExists)
}

func TestFind(t *testing.T) {
	t.Run("AccountProfiles", testAccountProfilesFind)
	t.Run("Accounts", testAccountsFind)
}

func TestBind(t *testing.T) {
	t.Run("AccountProfiles", testAccountProfilesBind)
	t.Run("Accounts", testAccountsBind)
}

func TestOne(t *testing.T) {
	t.Run("AccountProfiles", testAccountProfilesOne)
	t.Run("Accounts", testAccountsOne)
}

func TestAll(t *testing.T) {
	t.Run("AccountProfiles", testAccountProfilesAll)
	t.Run("Accounts", testAccountsAll)
}

func TestCount(t *testing.T) {
	t.Run("AccountProfiles", testAccountProfilesCount)
	t.Run("Accounts", testAccountsCount)
}

func TestHooks(t *testing.T) {
	t.Run("AccountProfiles", testAccountProfilesHooks)
	t.Run("Accounts", testAccountsHooks)
}

func TestInsert(t *testing.T) {
	t.Run("AccountProfiles", testAccountProfilesInsert)
	t.Run("AccountProfiles", testAccountProfilesInsertWhitelist)
	t.Run("Accounts", testAccountsInsert)
	t.Run("Accounts", testAccountsInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("AccountProfileToAccountUsingAccount", testAccountProfileToOneAccountUsingAccount)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("AccountToAccountProfiles", testAccountToManyAccountProfiles)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("AccountProfileToAccountUsingAccountProfiles", testAccountProfileToOneSetOpAccountUsingAccount)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("AccountProfileToAccountUsingAccountProfiles", testAccountProfileToOneRemoveOpAccountUsingAccount)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("AccountToAccountProfiles", testAccountToManyAddOpAccountProfiles)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("AccountToAccountProfiles", testAccountToManySetOpAccountProfiles)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("AccountToAccountProfiles", testAccountToManyRemoveOpAccountProfiles)
}

func TestReload(t *testing.T) {
	t.Run("AccountProfiles", testAccountProfilesReload)
	t.Run("Accounts", testAccountsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("AccountProfiles", testAccountProfilesReloadAll)
	t.Run("Accounts", testAccountsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("AccountProfiles", testAccountProfilesSelect)
	t.Run("Accounts", testAccountsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("AccountProfiles", testAccountProfilesUpdate)
	t.Run("Accounts", testAccountsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("AccountProfiles", testAccountProfilesSliceUpdateAll)
	t.Run("Accounts", testAccountsSliceUpdateAll)
}
