name: docker-compose-up-test
on: [push]
jobs:
  docker-compose-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - uses: actions/cache@v3
        id: cache-docker
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
      - name: build
        run: docker buildx bake --load --set *.cache-from=type=local,src=/tmp/.buildx-cache --set *.cache-to=type=local,dest=/tmp/.buildx-cache
      - name: cache load
        if: steps.cache-docker.outputs.cache-hit == 'true'
        run: docker load -i /tmp/.buildx-cache/*.tar
      - name: docker-compose up
        run: docker-compose up -d
