name: docker-compose-up-test
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  docker-compose-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - uses: actions/cache@v3
        id: cache-docker
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: docker-compose build
        run: docker-compose build
      - name: docker-compose up
        run: docker-compose up -d
