name: docker-compose-up-test
on: [push]
jobs:
  docker-compose-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - uses: actions/cache@v3
        id: cache-docker
        with:
          path: /tmp/images
          key: ${{ github.ref }}-${{ github.sha }}
      - name: build
        run: docker-compose build
      - name: cache save
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: docker save federation-gateway-re_backend:latest federation-gateway-re_products:latest federation-gateway-re_reviews:latest federation-gateway-re_accounts:latest federation-gateway-re_gateway:latest -o /tmp/images
      - name: cache load
        if: steps.cache-docker.outputs.cache-hit == 'true'
        run: docker load -i /tmp/images
      - name: docker-compose up
        run: docker-compose up -d
